### ISSUE TITLE
[Enhancement] Rendering performance on macOS

### ISSUE THREAD

**Issue by philipturner** [nanovis/SynopFrame#1]
Hello, I was contacted about maybe giving feedback to this repo. Great work, by the way. There are no installation instructions for the Mac, so I unfortunately cannot review the repository. The YouTube video looked like the UI was polished. I do not have much experience actually designing DNA nanotech, just experience evaluating speed of MD simulations. I cannot accurately evaluate how much SynopFrame helps people understand the DNA origami structure.

I can say that if users don't have installation instructions tailored to their platform, it decreases the chance they will use your tool. I recommend providing instructions for the Mac and regularly testing them. I should be able to start from scratch, and have your repository:

- 1) Guide me through installing all the dependencies
- 2) Show me how to use the macOS Terminal app
- 3) Show exact Shell commands for how to compile SynopFrame via CMake
- 4) Show how to run the compiled executable.

My repository at [openmm-metal](https://github.com/philipturner/openmm-metal) provides a good example of what that might look like.

Regarding performance, the Mac should not be as slow as it is. The [Nvidia 1050 Ti](https://www.techpowerup.com/gpu-specs/geforce-gtx-1050-ti.c2885) has 2.1 TFLOPS, 112 GB/s, 4 GB. The MacBook's [AMD 5300M](https://www.techpowerup.com/gpu-specs/radeon-rx-5300m.c3462) has 4.0 TFLOPS, 168 GB/s, 3 GB. If anything, the Mac should render faster. One unlikely, but possible cause is the simulation consuming slightly over 3 GB of RAM but not exceeding 4 GB.

I assume you're using the free Houdini Apprentice to render. There's probably a performance issue in the Houdini rendering backend, where it's optimized for Nvidia and/or Windows but not optimized for any other vendor/platform. I would recommend switching to a custom renderer, if you cannot resolve the performance issue. Vulkan would be a good cross-platform choice for people with C++ experience. Alternatively, Godot is less low-level, but Eric Drexler's using it for [MSEP](https://www.youtube.com/watch?v=HjgjtAk-lws).

I recently did some planning for a molecular renderer: https://github.com/philipturner/molecular-renderer. I highly recommend reading over the README. My biggest bottleneck was getting frames in at 120 FPS. For very large simulations, hard drive bandwidth would be a significant bottleneck. Make sure your simulation is stored on the SSD and not an HDD. I would also recommend storing the oxDNA simulation in a compressed format, to reduce SSD bandwidth for supermassive simulations.

**Comment by RodenLuo** [comment]
Hi Philip, Thanks for the feedback! [Openmm-metal](https://github.com/philipturner/openmm-metal) and [molecular-renderer](https://github.com/philipturner/molecular-renderer) are indeed documented well and focus more on Mac. SynopFrame, however, is neither a tool for designing nor for simulating molecules. It also focuses less on the rendering side (to which end we have [MesoCraft](https://www.nanovis.org/MesoCraft.html) that is capable of rendering 100+millions of atoms with 60+ FPS, such as rendering the [SARS-CoV-2 model](https://www.nanovis.org/SARS-CoV-2-model.html), which uses an impostor-based rendering approach that effectively reduces the number of triangle primitives) but more on the visualization side. It means we are exploring new ways of abstracting and presenting the original data (trajectories) that will ultimately result in less rendering overhead and better comprehensibility. With that, I'm relying on Houdini's fast prototyping capability to help my exploration of plenty of new ways of representing the same data and then iteratively checking with domain experts to filter those effective representations. So, right now, the whole solution is based on Houdini. Once it is proven effective, the next step would be creating a standalone tool or a web-based tool. 

I have the same feeling that Houdini is less tailored on Mac. 

The installation process will be very much like that for [Win](https://github.com/nanovis/SynopFrame/blob/main/Install-Win.md). But one will need to change the directory path to the Mac counterpart and perform the compilation of the plugin using clang (once the CMake-related folder path is correctly set, this compilation should be done very easily). I will try to get a Mac next to me again and update the doc in more detail. We can also set up a Zoom meeting where I can guide you through the installation.

**Comment by philipturner** [comment]
I'm don't know whether I'm willing to spend time compiling and testing the repository - I can write a technical review in 15-30 minutes, which is strangely faster and easier. I also don't want to force you to acquire hardware you don't currently own.

I'm not a domain expert in DNA nanotech and can't effectively evaluate this. But I can say that if you plan to build a standalone renderer, your software's long-term success looks very good. The current priority should be finishing your prototype on whatever platform/workflow is easiest for yourself.
